#!/bin/bash

function cli_usage {
    echo "Usage: $0 {command}"
    echo "Commands:"
    echo "  component              commands for components"
    echo "  help {command}         show help for a specific command"
}

function cli_help {
    cli_help_$1
}

function cli_help_component {
    echo "Usage: $0 generate {subcommand}"
    echo "Sub commands:"
    echo "  add [name]        generate a component template"
    echo "  list              list all available components"
}

function cli_component {
    if [ $# -lt 1 ]; then
        echo "Error: No subcommand provided for 'generate'."
        cli_help_generate
        exit 1
    fi

    case $1 in
        add)
            shift
            cli_generate_component "$@"
            ;;
        *)
            echo "Unknown subcommand: $1"
            cli_help_generate
            exit 1
            ;;
    esac
}

function cli_generate_component {
    if [ $# -lt 1 ]; then
        echo "Error: No component name provided."
        echo "Usage: $0 generate component [name]"
        exit 1
    fi

    local component_name=$1
    echo "Generating component template for '$component_name'..."

    pnpm dlx shadcn add $component_name
}

function cli {
    if [ $# -lt 1 ]; then
        cli_usage
        exit 1
    fi

    case $1 in
        component)
            shift
            cli_component "$@"
            ;;
        help)
            shift
            cli_help "$@"
            ;;
        *)
            echo "Unknown command: $1"
            cli_usage
            exit 1
            ;;
    esac
}

cli $@
