import { Raleway } from 'next/font/google';
import Header from '@/components/header';
import '@/assets/css/globals.css';
import Providers from '@/providers/providers';
import { Metadata } from 'next';
import CookieProvider from './_providers/CookieProvider';
import { Suspense } from 'react';

const raleway = Raleway({
  variable: '--font-raleway',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Ratel',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logos/favicon.ico" />
      </head>
      <body className={`${raleway.variable} antialiased bg-bg`}>
        <CookieProvider>
          <Providers>
            <Header />
            <Suspense>{children}</Suspense>
          </Providers>
        </CookieProvider>
      </body>
    </html>
  );
}
