'use client';

/* import { useCookie } from '@/lib/contexts/cookie-context'; */
import MyHome from './_components/MyHome';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function Home() {
  /* let cookie = useCookie(); */

  /* if (cookie?.isLoggedIn) {
   *   return <MyHome />;
   * } */

  return <MyHome />;
}
